//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3603 版自动生成。
// 
#pragma warning disable 1591

namespace OnLineExamBLLWS.DALWS_User {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DALWS_UserSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Users[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class DALWS_User : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelectAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update1OperationCompleted;
        
        private System.Threading.SendOrPostCallback delUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback selectUserPaperListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserPaperListOperationCompleted;
        
        private System.Threading.SendOrPostCallback delScoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback selectExamInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeclctCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertScoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectPwdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DALWS_User() {
            this.Url = global::OnLineExamBLLWS.Properties.Settings.Default.OnLineExamBLLWS_DALWS_User_DALWS_User;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectAllCompletedEventHandler SelectAllCompleted;
        
        /// <remarks/>
        public event SelectUserIDCompletedEventHandler SelectUserIDCompleted;
        
        /// <remarks/>
        public event SelectUserNameCompletedEventHandler SelectUserNameCompleted;
        
        /// <remarks/>
        public event SelectUserCompletedEventHandler SelectUserCompleted;
        
        /// <remarks/>
        public event insertUsersCompletedEventHandler insertUsersCompleted;
        
        /// <remarks/>
        public event LoginUserCompletedEventHandler LoginUserCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event Update1CompletedEventHandler Update1Completed;
        
        /// <remarks/>
        public event delUserIdCompletedEventHandler delUserIdCompleted;
        
        /// <remarks/>
        public event selectUserPaperListCompletedEventHandler selectUserPaperListCompleted;
        
        /// <remarks/>
        public event DeleteUserPaperListCompletedEventHandler DeleteUserPaperListCompleted;
        
        /// <remarks/>
        public event delScoresCompletedEventHandler delScoresCompleted;
        
        /// <remarks/>
        public event selectExamInfoCompletedEventHandler selectExamInfoCompleted;
        
        /// <remarks/>
        public event SeclctCheckCompletedEventHandler SeclctCheckCompleted;
        
        /// <remarks/>
        public event InsertScoreCompletedEventHandler InsertScoreCompleted;
        
        /// <remarks/>
        public event GetTimeCompletedEventHandler GetTimeCompleted;
        
        /// <remarks/>
        public event SelectPwdCompletedEventHandler SelectPwdCompleted;
        
        /// <remarks/>
        public event GetUserNameCompletedEventHandler GetUserNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Scores[] SelectAll(string PaperID) {
            object[] results = this.Invoke("SelectAll", new object[] {
                        PaperID});
            return ((Scores[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectAllAsync(string PaperID) {
            this.SelectAllAsync(PaperID, null);
        }
        
        /// <remarks/>
        public void SelectAllAsync(string PaperID, object userState) {
            if ((this.SelectAllOperationCompleted == null)) {
                this.SelectAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectAllOperationCompleted);
            }
            this.InvokeAsync("SelectAll", new object[] {
                        PaperID}, this.SelectAllOperationCompleted, userState);
        }
        
        private void OnSelectAllOperationCompleted(object arg) {
            if ((this.SelectAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectAllCompleted(this, new SelectAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Users[] SelectUserID(string userID) {
            object[] results = this.Invoke("SelectUserID", new object[] {
                        userID});
            return ((Users[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectUserIDAsync(string userID) {
            this.SelectUserIDAsync(userID, null);
        }
        
        /// <remarks/>
        public void SelectUserIDAsync(string userID, object userState) {
            if ((this.SelectUserIDOperationCompleted == null)) {
                this.SelectUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectUserIDOperationCompleted);
            }
            this.InvokeAsync("SelectUserID", new object[] {
                        userID}, this.SelectUserIDOperationCompleted, userState);
        }
        
        private void OnSelectUserIDOperationCompleted(object arg) {
            if ((this.SelectUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectUserIDCompleted(this, new SelectUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Users[] SelectUserName(string userName) {
            object[] results = this.Invoke("SelectUserName", new object[] {
                        userName});
            return ((Users[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectUserNameAsync(string userName) {
            this.SelectUserNameAsync(userName, null);
        }
        
        /// <remarks/>
        public void SelectUserNameAsync(string userName, object userState) {
            if ((this.SelectUserNameOperationCompleted == null)) {
                this.SelectUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectUserNameOperationCompleted);
            }
            this.InvokeAsync("SelectUserName", new object[] {
                        userName}, this.SelectUserNameOperationCompleted, userState);
        }
        
        private void OnSelectUserNameOperationCompleted(object arg) {
            if ((this.SelectUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectUserNameCompleted(this, new SelectUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Users[] SelectUser() {
            object[] results = this.Invoke("SelectUser", new object[0]);
            return ((Users[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectUserAsync() {
            this.SelectUserAsync(null);
        }
        
        /// <remarks/>
        public void SelectUserAsync(object userState) {
            if ((this.SelectUserOperationCompleted == null)) {
                this.SelectUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectUserOperationCompleted);
            }
            this.InvokeAsync("SelectUser", new object[0], this.SelectUserOperationCompleted, userState);
        }
        
        private void OnSelectUserOperationCompleted(object arg) {
            if ((this.SelectUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectUserCompleted(this, new SelectUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool insertUsers(Users user) {
            object[] results = this.Invoke("insertUsers", new object[] {
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertUsersAsync(Users user) {
            this.insertUsersAsync(user, null);
        }
        
        /// <remarks/>
        public void insertUsersAsync(Users user, object userState) {
            if ((this.insertUsersOperationCompleted == null)) {
                this.insertUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertUsersOperationCompleted);
            }
            this.InvokeAsync("insertUsers", new object[] {
                        user}, this.insertUsersOperationCompleted, userState);
        }
        
        private void OninsertUsersOperationCompleted(object arg) {
            if ((this.insertUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertUsersCompleted(this, new insertUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Users LoginUser(string UserID, string pwd) {
            object[] results = this.Invoke("LoginUser", new object[] {
                        UserID,
                        pwd});
            return ((Users)(results[0]));
        }
        
        /// <remarks/>
        public void LoginUserAsync(string UserID, string pwd) {
            this.LoginUserAsync(UserID, pwd, null);
        }
        
        /// <remarks/>
        public void LoginUserAsync(string UserID, string pwd, object userState) {
            if ((this.LoginUserOperationCompleted == null)) {
                this.LoginUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginUserOperationCompleted);
            }
            this.InvokeAsync("LoginUser", new object[] {
                        UserID,
                        pwd}, this.LoginUserOperationCompleted, userState);
        }
        
        private void OnLoginUserOperationCompleted(object arg) {
            if ((this.LoginUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginUserCompleted(this, new LoginUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(string UserPwd, string UserId) {
            this.Invoke("Update", new object[] {
                        UserPwd,
                        UserId});
        }
        
        /// <remarks/>
        public void UpdateAsync(string UserPwd, string UserId) {
            this.UpdateAsync(UserPwd, UserId, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(string UserPwd, string UserId, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        UserPwd,
                        UserId}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update1(string UserId, string UserPwd) {
            object[] results = this.Invoke("Update1", new object[] {
                        UserId,
                        UserPwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Update1Async(string UserId, string UserPwd) {
            this.Update1Async(UserId, UserPwd, null);
        }
        
        /// <remarks/>
        public void Update1Async(string UserId, string UserPwd, object userState) {
            if ((this.Update1OperationCompleted == null)) {
                this.Update1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate1OperationCompleted);
            }
            this.InvokeAsync("Update1", new object[] {
                        UserId,
                        UserPwd}, this.Update1OperationCompleted, userState);
        }
        
        private void OnUpdate1OperationCompleted(object arg) {
            if ((this.Update1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update1Completed(this, new Update1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool delUserId(string UserId) {
            object[] results = this.Invoke("delUserId", new object[] {
                        UserId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void delUserIdAsync(string UserId) {
            this.delUserIdAsync(UserId, null);
        }
        
        /// <remarks/>
        public void delUserIdAsync(string UserId, object userState) {
            if ((this.delUserIdOperationCompleted == null)) {
                this.delUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OndelUserIdOperationCompleted);
            }
            this.InvokeAsync("delUserId", new object[] {
                        UserId}, this.delUserIdOperationCompleted, userState);
        }
        
        private void OndelUserIdOperationCompleted(object arg) {
            if ((this.delUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delUserIdCompleted(this, new delUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectUserPaperList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAnswer[] selectUserPaperList() {
            object[] results = this.Invoke("selectUserPaperList", new object[0]);
            return ((UserAnswer[])(results[0]));
        }
        
        /// <remarks/>
        public void selectUserPaperListAsync() {
            this.selectUserPaperListAsync(null);
        }
        
        /// <remarks/>
        public void selectUserPaperListAsync(object userState) {
            if ((this.selectUserPaperListOperationCompleted == null)) {
                this.selectUserPaperListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnselectUserPaperListOperationCompleted);
            }
            this.InvokeAsync("selectUserPaperList", new object[0], this.selectUserPaperListOperationCompleted, userState);
        }
        
        private void OnselectUserPaperListOperationCompleted(object arg) {
            if ((this.selectUserPaperListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.selectUserPaperListCompleted(this, new selectUserPaperListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserPaperList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUserPaperList(string UsersID, int PapersID) {
            object[] results = this.Invoke("DeleteUserPaperList", new object[] {
                        UsersID,
                        PapersID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserPaperListAsync(string UsersID, int PapersID) {
            this.DeleteUserPaperListAsync(UsersID, PapersID, null);
        }
        
        /// <remarks/>
        public void DeleteUserPaperListAsync(string UsersID, int PapersID, object userState) {
            if ((this.DeleteUserPaperListOperationCompleted == null)) {
                this.DeleteUserPaperListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserPaperListOperationCompleted);
            }
            this.InvokeAsync("DeleteUserPaperList", new object[] {
                        UsersID,
                        PapersID}, this.DeleteUserPaperListOperationCompleted, userState);
        }
        
        private void OnDeleteUserPaperListOperationCompleted(object arg) {
            if ((this.DeleteUserPaperListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserPaperListCompleted(this, new DeleteUserPaperListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delScores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool delScores(string UserID) {
            object[] results = this.Invoke("delScores", new object[] {
                        UserID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void delScoresAsync(string UserID) {
            this.delScoresAsync(UserID, null);
        }
        
        /// <remarks/>
        public void delScoresAsync(string UserID, object userState) {
            if ((this.delScoresOperationCompleted == null)) {
                this.delScoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OndelScoresOperationCompleted);
            }
            this.InvokeAsync("delScores", new object[] {
                        UserID}, this.delScoresOperationCompleted, userState);
        }
        
        private void OndelScoresOperationCompleted(object arg) {
            if ((this.delScoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delScoresCompleted(this, new delScoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectExamInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAnswer[] selectExamInfo(string name) {
            object[] results = this.Invoke("selectExamInfo", new object[] {
                        name});
            return ((UserAnswer[])(results[0]));
        }
        
        /// <remarks/>
        public void selectExamInfoAsync(string name) {
            this.selectExamInfoAsync(name, null);
        }
        
        /// <remarks/>
        public void selectExamInfoAsync(string name, object userState) {
            if ((this.selectExamInfoOperationCompleted == null)) {
                this.selectExamInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnselectExamInfoOperationCompleted);
            }
            this.InvokeAsync("selectExamInfo", new object[] {
                        name}, this.selectExamInfoOperationCompleted, userState);
        }
        
        private void OnselectExamInfoOperationCompleted(object arg) {
            if ((this.selectExamInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.selectExamInfoCompleted(this, new selectExamInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeclctCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SeclctCheck(string userId, int paperId) {
            object[] results = this.Invoke("SeclctCheck", new object[] {
                        userId,
                        paperId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SeclctCheckAsync(string userId, int paperId) {
            this.SeclctCheckAsync(userId, paperId, null);
        }
        
        /// <remarks/>
        public void SeclctCheckAsync(string userId, int paperId, object userState) {
            if ((this.SeclctCheckOperationCompleted == null)) {
                this.SeclctCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeclctCheckOperationCompleted);
            }
            this.InvokeAsync("SeclctCheck", new object[] {
                        userId,
                        paperId}, this.SeclctCheckOperationCompleted, userState);
        }
        
        private void OnSeclctCheckOperationCompleted(object arg) {
            if ((this.SeclctCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeclctCheckCompleted(this, new SeclctCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertScore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertScore(Scores score, string PaperName, string userId, int paperId) {
            object[] results = this.Invoke("InsertScore", new object[] {
                        score,
                        PaperName,
                        userId,
                        paperId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertScoreAsync(Scores score, string PaperName, string userId, int paperId) {
            this.InsertScoreAsync(score, PaperName, userId, paperId, null);
        }
        
        /// <remarks/>
        public void InsertScoreAsync(Scores score, string PaperName, string userId, int paperId, object userState) {
            if ((this.InsertScoreOperationCompleted == null)) {
                this.InsertScoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertScoreOperationCompleted);
            }
            this.InvokeAsync("InsertScore", new object[] {
                        score,
                        PaperName,
                        userId,
                        paperId}, this.InsertScoreOperationCompleted, userState);
        }
        
        private void OnInsertScoreOperationCompleted(object arg) {
            if ((this.InsertScoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertScoreCompleted(this, new InsertScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTime(int id) {
            object[] results = this.Invoke("GetTime", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeAsync(int id) {
            this.GetTimeAsync(id, null);
        }
        
        /// <remarks/>
        public void GetTimeAsync(int id, object userState) {
            if ((this.GetTimeOperationCompleted == null)) {
                this.GetTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeOperationCompleted);
            }
            this.InvokeAsync("GetTime", new object[] {
                        id}, this.GetTimeOperationCompleted, userState);
        }
        
        private void OnGetTimeOperationCompleted(object arg) {
            if ((this.GetTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeCompleted(this, new GetTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectPwd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SelectPwd(string Pwd) {
            object[] results = this.Invoke("SelectPwd", new object[] {
                        Pwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SelectPwdAsync(string Pwd) {
            this.SelectPwdAsync(Pwd, null);
        }
        
        /// <remarks/>
        public void SelectPwdAsync(string Pwd, object userState) {
            if ((this.SelectPwdOperationCompleted == null)) {
                this.SelectPwdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectPwdOperationCompleted);
            }
            this.InvokeAsync("SelectPwd", new object[] {
                        Pwd}, this.SelectPwdOperationCompleted, userState);
        }
        
        private void OnSelectPwdOperationCompleted(object arg) {
            if ((this.SelectPwdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectPwdCompleted(this, new SelectPwdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserName(string UserID) {
            object[] results = this.Invoke("GetUserName", new object[] {
                        UserID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserNameAsync(string UserID) {
            this.GetUserNameAsync(UserID, null);
        }
        
        /// <remarks/>
        public void GetUserNameAsync(string UserID, object userState) {
            if ((this.GetUserNameOperationCompleted == null)) {
                this.GetUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserNameOperationCompleted);
            }
            this.InvokeAsync("GetUserName", new object[] {
                        UserID}, this.GetUserNameOperationCompleted, userState);
        }
        
        private void OnGetUserNameOperationCompleted(object arg) {
            if ((this.GetUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserNameCompleted(this, new GetUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Scores {
        
        private int idField;
        
        private string userIDField;
        
        private string userNameField;
        
        private int paperIDField;
        
        private int scoreField;
        
        private System.DateTime examTimeField;
        
        private System.DateTime judgeTimeField;
        
        private string pingYuField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public int PaperID {
            get {
                return this.paperIDField;
            }
            set {
                this.paperIDField = value;
            }
        }
        
        /// <remarks/>
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExamTime {
            get {
                return this.examTimeField;
            }
            set {
                this.examTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime JudgeTime {
            get {
                return this.judgeTimeField;
            }
            set {
                this.judgeTimeField = value;
            }
        }
        
        /// <remarks/>
        public string PingYu {
            get {
                return this.pingYuField;
            }
            set {
                this.pingYuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAnswer {
        
        private int idField;
        
        private string userIDField;
        
        private int paperIDField;
        
        private string typeField;
        
        private int titleIDField;
        
        private int markField;
        
        private string userAnswersField;
        
        private System.DateTime examTimeField;
        
        private string userNameField;
        
        private string paperNameField;
        
        private int courseIDField;
        
        private byte paperStateField;
        
        private string userPwdField;
        
        private int roleIdField;
        
        private int scoreField;
        
        private System.DateTime judgeTimeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public int PaperID {
            get {
                return this.paperIDField;
            }
            set {
                this.paperIDField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int TitleID {
            get {
                return this.titleIDField;
            }
            set {
                this.titleIDField = value;
            }
        }
        
        /// <remarks/>
        public int Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        public string UserAnswers {
            get {
                return this.userAnswersField;
            }
            set {
                this.userAnswersField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExamTime {
            get {
                return this.examTimeField;
            }
            set {
                this.examTimeField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PaperName {
            get {
                return this.paperNameField;
            }
            set {
                this.paperNameField = value;
            }
        }
        
        /// <remarks/>
        public int CourseID {
            get {
                return this.courseIDField;
            }
            set {
                this.courseIDField = value;
            }
        }
        
        /// <remarks/>
        public byte PaperState {
            get {
                return this.paperStateField;
            }
            set {
                this.paperStateField = value;
            }
        }
        
        /// <remarks/>
        public string UserPwd {
            get {
                return this.userPwdField;
            }
            set {
                this.userPwdField = value;
            }
        }
        
        /// <remarks/>
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime JudgeTime {
            get {
                return this.judgeTimeField;
            }
            set {
                this.judgeTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Role {
        
        private int roleIdField;
        
        private string roleNameField;
        
        private int hasDuty_DepartmentManageField;
        
        private int hasDuty_UserManageField;
        
        private int hasDuty_RoleManageField;
        
        private int hasDuty_RoleField;
        
        private int hasDuty_UserScoreField;
        
        private int hasDuty_CourseManageField;
        
        private int hasDuty_PaperSetupField;
        
        private int hasDuty_PaperListsField;
        
        private int hasDuty_UserPaperListField;
        
        private int hasDuty_SingleSelectManageField;
        
        private int hasDuty_MultiSelectManageField;
        
        private int hasDuty_FillBlankManageField;
        
        private int hasDuty_JudgeManageField;
        
        private int hasDuty_QuestionManageField;
        
        /// <remarks/>
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_DepartmentManage {
            get {
                return this.hasDuty_DepartmentManageField;
            }
            set {
                this.hasDuty_DepartmentManageField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_UserManage {
            get {
                return this.hasDuty_UserManageField;
            }
            set {
                this.hasDuty_UserManageField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_RoleManage {
            get {
                return this.hasDuty_RoleManageField;
            }
            set {
                this.hasDuty_RoleManageField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_Role {
            get {
                return this.hasDuty_RoleField;
            }
            set {
                this.hasDuty_RoleField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_UserScore {
            get {
                return this.hasDuty_UserScoreField;
            }
            set {
                this.hasDuty_UserScoreField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_CourseManage {
            get {
                return this.hasDuty_CourseManageField;
            }
            set {
                this.hasDuty_CourseManageField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_PaperSetup {
            get {
                return this.hasDuty_PaperSetupField;
            }
            set {
                this.hasDuty_PaperSetupField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_PaperLists {
            get {
                return this.hasDuty_PaperListsField;
            }
            set {
                this.hasDuty_PaperListsField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_UserPaperList {
            get {
                return this.hasDuty_UserPaperListField;
            }
            set {
                this.hasDuty_UserPaperListField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_SingleSelectManage {
            get {
                return this.hasDuty_SingleSelectManageField;
            }
            set {
                this.hasDuty_SingleSelectManageField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_MultiSelectManage {
            get {
                return this.hasDuty_MultiSelectManageField;
            }
            set {
                this.hasDuty_MultiSelectManageField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_FillBlankManage {
            get {
                return this.hasDuty_FillBlankManageField;
            }
            set {
                this.hasDuty_FillBlankManageField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_JudgeManage {
            get {
                return this.hasDuty_JudgeManageField;
            }
            set {
                this.hasDuty_JudgeManageField = value;
            }
        }
        
        /// <remarks/>
        public int HasDuty_QuestionManage {
            get {
                return this.hasDuty_QuestionManageField;
            }
            set {
                this.hasDuty_QuestionManageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Users {
        
        private Role roleField;
        
        private string userIDField;
        
        private string userPwdField;
        
        private string userNameField;
        
        private int roleIdField;
        
        private string roleNameField;
        
        private object[] dutiesField;
        
        /// <remarks/>
        public Role Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserPwd {
            get {
                return this.userPwdField;
            }
            set {
                this.userPwdField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public object[] Duties {
            get {
                return this.dutiesField;
            }
            set {
                this.dutiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SelectAllCompletedEventHandler(object sender, SelectAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Scores[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Scores[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SelectUserIDCompletedEventHandler(object sender, SelectUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Users[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Users[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SelectUserNameCompletedEventHandler(object sender, SelectUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Users[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Users[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SelectUserCompletedEventHandler(object sender, SelectUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Users[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Users[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void insertUsersCompletedEventHandler(object sender, insertUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LoginUserCompletedEventHandler(object sender, LoginUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Users Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Users)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void Update1CompletedEventHandler(object sender, Update1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void delUserIdCompletedEventHandler(object sender, delUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void selectUserPaperListCompletedEventHandler(object sender, selectUserPaperListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class selectUserPaperListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal selectUserPaperListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAnswer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAnswer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void DeleteUserPaperListCompletedEventHandler(object sender, DeleteUserPaperListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserPaperListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserPaperListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void delScoresCompletedEventHandler(object sender, delScoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void selectExamInfoCompletedEventHandler(object sender, selectExamInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class selectExamInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal selectExamInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAnswer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAnswer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SeclctCheckCompletedEventHandler(object sender, SeclctCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeclctCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeclctCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void InsertScoreCompletedEventHandler(object sender, InsertScoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetTimeCompletedEventHandler(object sender, GetTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SelectPwdCompletedEventHandler(object sender, SelectPwdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectPwdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectPwdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetUserNameCompletedEventHandler(object sender, GetUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591